version: 2.1 # use CircleCI 2.1
jobs: # a collection of steps
  build: # runs not using Workflows must have a `build` job as entry point
    working_directory: ~/sites/haven-development # directory where steps will run
    docker: # run the steps with Docker
      - image: circleci/node:10.16.3
    steps: # a collection of executable commands
      - checkout # special step to check out source code to working directory
      - run: yarn
      - run: yarn test
      - persist_to_workspace: 
          root: ~/sites/haven-development
          paths: 
            - node_modules
      - store_test_results: 
          path: ~/sites/haven-development/coverage/junit.xml
 