version: 2.1

orbs:
  aws-s3: circleci/aws-s3@1.0.15
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master

jobs:
  build:
    working_directory: ~/haven-development
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run: yarn
      - run: yarn test
      - run: yarn build
      - persist_to_workspace:
          root: ~/haven-development
          paths: 
            - node_modules
      - store_test_results: 
          path: ~/haven-development/coverage/junit.xml
  deploy:
    docker:
      - image: 'cimg/python:3.6'
    steps:
      - checkout
      - aws-s3/sync:
          from: bucket
          to: 's3://haven-development/website'
          overwrite: true